### ISSUE TITLE
  "django-fieldsignals signals must be connected after the app cache is ready. "

### ISSUE THREAD

**Issue by barbouche** [craigds/django-fieldsignals#18]
"django-fieldsignals signals must be connected after the app cache is ready. "
hajj_1        | django.core.exceptions.AppRegistryNotReady: django-fieldsignals signals must be connected after the app cache is ready. Connect the signal in your AppConfig.ready() handler.

Hello, please somone can help me, i tiy to use signalfiled libarry to get changed filed but it dosent work , it show me the eror above, i tied to change init file and app file but nothings

**Comment by craigds** [comment]
I think this is covered in this section of the README: https://github.com/craigds/django-fieldsignals#where-should-my-signals-code-live
