### ISSUE TITLE
get_fields() AppRegistryNotReady: Models aren't loaded yet.

### ISSUE THREAD

**Issue by 7wonders** [craigds/django-fieldsignals#4]
Seems to be a problem with get_fields not wanting to run on django 1.8.8 :(

fieldsignals/signals.py", line 40

**Comment by craigds** [comment]
Hi, is this with the new 0.2.1?

Can you post the traceback?

**Comment by 7wonders** [comment]
Its ok. After doing what I should have done a long time ago and moving my signals into AppConfig.ready() everything is working again now :) Sorry for the bother!
