### ISSUE TITLE
Fieldsignals in Views

### ISSUE THREAD

**Issue by invious** [craigds/django-fieldsignals#7]
I have some code that will update a model with data from a server. I want to call this refresh button using an ajax call. Right now I just `update_or_create` on the model, and I presume the print all changes code I modeled after the example you gave will run.

```
from fieldsignals import pre_save_changed

    def print_all_field_changes(sender, instance, changed_fields=None, **kwargs):
        for field, (old, new) in changed_fields.items():
            print "%s changed from %s to %s" % (field.name, old, new)

    pre_save_changed.connect(print_all_field_changes, sender=Poll)
```

How do I return the fact that changes have happened to the user?

```
def refresh_models(request):
    update_db()
```

**Comment by craigds** [comment]
fieldsignals operates at the model level, so you just need to communicate the change back to your view somehow. 

I guess if I was doing it I'd just set an attribute on the model instance so your view knows what changed:

`instance._changed_fields = changed_fields`
Then your view can inspect that attribute on the instance that `update_or_create` returns.
